module.exports = Object.freeze({
    topRated: "https://api.themoviedb.org/3/movie/top_rated",
    categories: "https://api.themoviedb.org/3/genre/movie/list",
    // popular: "https://api.themoviedb.org/3/movie/popular",
    popular: "https://api.themoviedb.org/3/movie/popular",
    upcoming: "https://api.themoviedb.org/3/movie/upcoming",
    filmDetails: "https://api.themoviedb.org/3/movie/",
    filmTrailer: "https://www.youtube.com/embed/",
    autoPlay: "?autoplay=1",
    posterUrl: "https://image.tmdb.org/t/p/original",
    findFilm: "https://api.themoviedb.org/3/search/movie?query=",
    adultTrue: "&include_adult=false&",
    trLanguage: "?language=tr-TR",
    enLanguage: "?language=en-US",
    pageText: "&page=",
    tr: {
        search: "Ara",
        home: "Ana Sayfa",
        popular: "Popüler Filmler",
        watchlist: "İzleme Listem",
        categories: "Kategoriler",
        signUp: "Kaydol",
        profile: "Profil",
        details: "Detaylar",
        nextPage: "Sonraki",
        previousPage: "Önceki",
        developedBy: "tarafından geliştirildi.",
        summary: "Özet:",
        revenue: "Hasılat:",
        runtime: "Süre:",
        voteCount: "Oy Sayısı:",
        voteAverage: "Puan:",
        prodCompanies: "Prodüksiyon Şirketleri:",
        prodCountries: "Prodüksiyon Ülkeleri:",
        releaseDate: "Vizyon Tarihi:"
    },
    en: {
        search: "Search",
        home: "Home",
        popular: "Populars",
        watchlist: "My Watchlist",
        categories: "Categories",
        signUp: "Sign Up",
        profile: "Profile",
        details: "Details",
        nextPage: "Next",
        previousPage: "Previous",
        developedBy: "Developed by",
        summary: "Summary:",
        revenue: "Revenue:",
        runtime: "Runtime:",
        voteCount: "Vote Count:",
        voteAverage: "Vote Average:",
        prodCompanies: "Production Companies:",
        prodCountries: "Production Countries:",
        releaseDate: "Release Date:"
    }
});